version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email_processor_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/opt/app/src
      - ./config:/opt/app/config
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro # Монтируем ключ в read-only
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: email_processor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: email_processor_adminer
    ports:
      - "8080:8080"
    restart: unless-stopped

  sftp:
    image: atmoz/sftp
    container_name: email_processor_sftp
    volumes:
      - ./storage/sftp_upload:/home/sftpuser/upload
      - ~/.ssh/id_rsa.pub:/home/sftpuser/.ssh/keys/id_rsa.pub:ro
    ports:
      - "2222:22"
    command: sftpuser:pass:1001

volumes:
  postgres_data:
